// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThePLeagueDataCore;

namespace ThePLeagueDataCore.Migrations
{
    [DbContext(typeof(ThePLeagueContext))]
    [Migration("20191231031313_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Gallery.LeagueImage", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Big");

                    b.Property<string>("CloudinaryPublicId");

                    b.Property<bool?>("Delete");

                    b.Property<string>("Format");

                    b.Property<string>("HashTag");

                    b.Property<int>("Height");

                    b.Property<string>("Medium");

                    b.Property<string>("Name");

                    b.Property<long?>("OrderId");

                    b.Property<string>("ResourceType");

                    b.Property<long?>("Size");

                    b.Property<string>("Small");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("LeagueImages");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.GearImage", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Big");

                    b.Property<string>("CloudinaryPublicId");

                    b.Property<string>("Format");

                    b.Property<long?>("GearItemId");

                    b.Property<int>("Height");

                    b.Property<string>("Medium");

                    b.Property<string>("Name");

                    b.Property<string>("ResourceType");

                    b.Property<long?>("Size");

                    b.Property<string>("Small");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.ToTable("GearImages");

                    b.HasData(
                        new
                        {
                            Id = 11231L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 1L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2322L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 1L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34323L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 1L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11232L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 2L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2323L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 2L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34324L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 2L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11233L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 3L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2324L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 3L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34325L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 3L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11234L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 4L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2325L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 4L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34326L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 4L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11235L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 5L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2326L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 5L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34327L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 5L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11236L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 6L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2327L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 6L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34328L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 6L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11237L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 7L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2328L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 7L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34329L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 7L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11238L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 8L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2329L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 8L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34330L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 8L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11239L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 9L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2330L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 9L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34331L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 9L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11240L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 10L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2331L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 10L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34332L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 10L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 11241L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 11L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wow",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 2332L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 11L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwee",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        },
                        new
                        {
                            Id = 34333L,
                            Big = "https://via.placeholder.com/300.png/09f/fff",
                            GearItemId = 11L,
                            Height = 0,
                            Medium = "https://via.placeholder.com/300.png/09f/fff",
                            Name = "wowwaw",
                            Size = 19392L,
                            Small = "https://via.placeholder.com/300.png/09f/fff",
                            Type = "png",
                            Url = "https://via.placeholder.com/300.png/09f/fff",
                            Width = 0
                        });
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.GearItem", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("InStock");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.ToTable("GearItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            InStock = true,
                            Name = "T-shirt",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2L,
                            InStock = false,
                            Name = "Pants",
                            Price = 26m
                        },
                        new
                        {
                            Id = 3L,
                            InStock = true,
                            Name = "Hat",
                            Price = 27m
                        },
                        new
                        {
                            Id = 4L,
                            InStock = false,
                            Name = "Jorts",
                            Price = 28m
                        },
                        new
                        {
                            Id = 5L,
                            InStock = true,
                            Name = "Long Sleeve",
                            Price = 29m
                        },
                        new
                        {
                            Id = 6L,
                            InStock = false,
                            Name = "Shoes",
                            Price = 30m
                        },
                        new
                        {
                            Id = 7L,
                            InStock = true,
                            Name = "Trousers",
                            Price = 31m
                        },
                        new
                        {
                            Id = 8L,
                            InStock = false,
                            Name = "Zip-Up",
                            Price = 32m
                        },
                        new
                        {
                            Id = 9L,
                            InStock = true,
                            Name = "Track Jacket",
                            Price = 33m
                        },
                        new
                        {
                            Id = 10L,
                            InStock = false,
                            Name = "Cut off",
                            Price = 34m
                        },
                        new
                        {
                            Id = 11L,
                            InStock = true,
                            Name = "Suprirse",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.GearSize", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available");

                    b.Property<string>("Color");

                    b.Property<long?>("GearItemId");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.ToTable("GearSizes");

                    b.HasData(
                        new
                        {
                            Id = 102L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 1L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1334L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 1L,
                            Size = 5
                        },
                        new
                        {
                            Id = 44L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 1L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45678L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 1L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9099L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 1L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85843L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 1L,
                            Size = 1
                        },
                        new
                        {
                            Id = 103L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 2L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1335L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 2L,
                            Size = 5
                        },
                        new
                        {
                            Id = 45L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 2L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45679L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 2L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9100L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 2L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85844L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 2L,
                            Size = 1
                        },
                        new
                        {
                            Id = 104L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 3L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1336L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 3L,
                            Size = 5
                        },
                        new
                        {
                            Id = 46L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 3L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45680L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 3L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9101L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 3L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85845L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 3L,
                            Size = 1
                        },
                        new
                        {
                            Id = 105L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 4L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1337L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 4L,
                            Size = 5
                        },
                        new
                        {
                            Id = 47L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 4L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45681L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 4L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9102L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 4L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85846L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 4L,
                            Size = 1
                        },
                        new
                        {
                            Id = 106L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 5L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1338L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 5L,
                            Size = 5
                        },
                        new
                        {
                            Id = 48L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 5L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45682L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 5L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9103L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 5L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85847L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 5L,
                            Size = 1
                        },
                        new
                        {
                            Id = 107L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 6L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1339L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 6L,
                            Size = 5
                        },
                        new
                        {
                            Id = 49L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 6L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45683L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 6L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9104L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 6L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85848L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 6L,
                            Size = 1
                        },
                        new
                        {
                            Id = 108L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 7L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1340L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 7L,
                            Size = 5
                        },
                        new
                        {
                            Id = 50L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 7L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45684L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 7L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9105L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 7L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85849L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 7L,
                            Size = 1
                        },
                        new
                        {
                            Id = 109L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 8L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1341L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 8L,
                            Size = 5
                        },
                        new
                        {
                            Id = 51L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 8L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45685L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 8L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9106L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 8L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85850L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 8L,
                            Size = 1
                        },
                        new
                        {
                            Id = 110L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 9L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1342L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 9L,
                            Size = 5
                        },
                        new
                        {
                            Id = 52L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 9L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45686L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 9L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9107L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 9L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85851L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 9L,
                            Size = 1
                        },
                        new
                        {
                            Id = 111L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 10L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1343L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 10L,
                            Size = 5
                        },
                        new
                        {
                            Id = 53L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 10L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45687L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 10L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9108L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 10L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85852L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 10L,
                            Size = 1
                        },
                        new
                        {
                            Id = 112L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 11L,
                            Size = 4
                        },
                        new
                        {
                            Id = 1344L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 11L,
                            Size = 5
                        },
                        new
                        {
                            Id = 54L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 11L,
                            Size = 6
                        },
                        new
                        {
                            Id = 45688L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 11L,
                            Size = 3
                        },
                        new
                        {
                            Id = 9109L,
                            Available = false,
                            Color = "warn",
                            GearItemId = 11L,
                            Size = 2
                        },
                        new
                        {
                            Id = 85853L,
                            Available = true,
                            Color = "warn",
                            GearItemId = 11L,
                            Size = 1
                        });
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.PreOrder", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("GearItemId");

                    b.Property<long?>("Quantity");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.ToTable("PreOrders");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.PreOrderContact", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<long?>("PreOrderId");

                    b.Property<int>("PreferredContact");

                    b.HasKey("Id");

                    b.HasIndex("PreOrderId")
                        .IsUnique()
                        .HasFilter("[PreOrderId] IS NOT NULL");

                    b.ToTable("PreOrderContacts");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.GameDay", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GamesDay");

                    b.Property<string>("LeagueSessionScheduleId");

                    b.HasKey("Id");

                    b.HasIndex("LeagueSessionScheduleId");

                    b.ToTable("GameDays");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.GameTime", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameDayId");

                    b.Property<DateTime>("GamesTime");

                    b.HasKey("Id");

                    b.HasIndex("GameDayId");

                    b.ToTable("GameTimes");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.League", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<string>("SportTypeID");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("SportTypeID");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Monday",
                            Selected = false,
                            SportTypeID = "1",
                            Type = "Basketball"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Tuesday",
                            Selected = false,
                            SportTypeID = "1",
                            Type = "Basketball"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Wednesday",
                            Selected = false,
                            SportTypeID = "1",
                            Type = "Basketball"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Thursday",
                            Selected = false,
                            SportTypeID = "2",
                            Type = "Volleyball"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Friday",
                            Selected = false,
                            SportTypeID = "2",
                            Type = "Volleyball"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Saturday",
                            Selected = false,
                            SportTypeID = "2",
                            Type = "Volleyball"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Sunday",
                            Selected = false,
                            SportTypeID = "3",
                            Type = "Soccer"
                        });
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.LeagueSessionSchedule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<bool>("ByeWeeks");

                    b.Property<string>("LeagueID");

                    b.Property<long?>("NumberOfWeeks");

                    b.Property<DateTime>("SessionEnd");

                    b.Property<DateTime>("SessionStart");

                    b.HasKey("Id");

                    b.HasIndex("LeagueID");

                    b.ToTable("LeagueSessions");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.Match", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwayTeamId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("HomeTeamId");

                    b.Property<string>("LeagueID");

                    b.Property<string>("LeagueSessionScheduleId");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueID");

                    b.HasIndex("LeagueSessionScheduleId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.SportType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SportTypes");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Volleyball"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Soccer"
                        });
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.Team", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("LeagueID");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.HasKey("Id");

                    b.HasIndex("LeagueID");

                    b.ToTable("Teams");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Team");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.TeamSession", b =>
                {
                    b.Property<string>("TeamId");

                    b.Property<string>("LeagueSessionScheduleId");

                    b.Property<string>("Id");

                    b.HasKey("TeamId", "LeagueSessionScheduleId");

                    b.HasIndex("LeagueSessionScheduleId");

                    b.ToTable("TeamsSessions");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.TeamSignUp.Contact", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<int>("PreferredContact");

                    b.Property<long?>("TeamSignUpFormId");

                    b.HasKey("Id");

                    b.HasIndex("TeamSignUpFormId")
                        .IsUnique()
                        .HasFilter("[TeamSignUpFormId] IS NOT NULL");

                    b.ToTable("TeamsContact");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.TeamSignUp.TeamSignUpForm", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TeamSignUpForms");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.AwayTeam", b =>
                {
                    b.HasBaseType("ThePLeagueDomain.Models.Schedule.Team");

                    b.HasDiscriminator().HasValue("AwayTeam");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.HomeTeam", b =>
                {
                    b.HasBaseType("ThePLeagueDomain.Models.Schedule.Team");

                    b.HasDiscriminator().HasValue("HomeTeam");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThePLeagueDomain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.GearImage", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Merchandise.GearItem", "GearItem")
                        .WithMany("Images")
                        .HasForeignKey("GearItemId");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.GearSize", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Merchandise.GearItem", "GearItem")
                        .WithMany("Sizes")
                        .HasForeignKey("GearItemId");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Merchandise.PreOrderContact", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Merchandise.PreOrder", "PreOrder")
                        .WithOne("Contact")
                        .HasForeignKey("ThePLeagueDomain.Models.Merchandise.PreOrderContact", "PreOrderId");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.GameDay", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.LeagueSessionSchedule")
                        .WithMany("GamesDays")
                        .HasForeignKey("LeagueSessionScheduleId");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.GameTime", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.GameDay")
                        .WithMany("GamesTimes")
                        .HasForeignKey("GameDayId");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.League", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.SportType", "SportType")
                        .WithMany("Leagues")
                        .HasForeignKey("SportTypeID");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.LeagueSessionSchedule", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.League")
                        .WithMany("Sessions")
                        .HasForeignKey("LeagueID");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.Match", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.AwayTeam", "AwayTeam")
                        .WithMany("Matches")
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("ThePLeagueDomain.Models.Schedule.HomeTeam", "HomeTeam")
                        .WithMany("Matches")
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("ThePLeagueDomain.Models.Schedule.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueID");

                    b.HasOne("ThePLeagueDomain.Models.Schedule.LeagueSessionSchedule")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueSessionScheduleId");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.Team", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueID");
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.Schedule.TeamSession", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.Schedule.LeagueSessionSchedule", "LeagueSessionSchedule")
                        .WithMany("TeamsSessions")
                        .HasForeignKey("LeagueSessionScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThePLeagueDomain.Models.Schedule.Team", "Team")
                        .WithMany("TeamsSessions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThePLeagueDomain.Models.TeamSignUp.Contact", b =>
                {
                    b.HasOne("ThePLeagueDomain.Models.TeamSignUp.TeamSignUpForm", "TeamSignUpForm")
                        .WithOne("Contact")
                        .HasForeignKey("ThePLeagueDomain.Models.TeamSignUp.Contact", "TeamSignUpFormId");
                });
#pragma warning restore 612, 618
        }
    }
}
